[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain.workspace = true
sea-orm.workspace = true
anyhow.workspace = true
chrono.workspace = true
tracing.workspace = true

[dev-dependencies]
domain = { workspace = true, features = ["test-support"] }
