[workspace]
members = ["crates/domain", "crates/usecase", "crates/presentation"]

[workspace.dependencies]
getset = "0.1.4"
chrono = "0.4.39"
anyhow = "1.0.95"
thiserror = "2.0.11"
xid = "1.1.1"
tokio = { version = "1.47.1", features = ["full"] }
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mockall = "0.13.1"
