services:
  db:
    image: postgres:16
    container_name: xlair-dev-db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: rust:1.90
    container_name: xlair-dev-migrator
    working_dir: /workspace
    volumes:
      - .:/workspace
      - cargo-target:/workspace/target
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "cargo run -p migration -- refresh"
    restart: "no"

volumes:
  cargo-target:
