services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${APP_IMAGE}:${IMAGE_TAG}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped

  migrator:
    image: ${APP_IMAGE}:${IMAGE_TAG}
    entrypoint: ["/app/migrate"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migration
    restart: "no"

volumes:
  db-data:
