//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::{
    musics::Entity as Musics, records::Entity as Records, sheets::Entity as Sheets,
    user_play_options::Entity as UserPlayOptions, users::Entity as Users,
};
