//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "clear_type")]
pub enum ClearType {
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "clear")]
    Clear,
    #[sea_orm(string_value = "full_combo")]
    FullCombo,
    #[sea_orm(string_value = "all_perfect")]
    AllPerfect,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "difficulty")]
pub enum Difficulty {
    #[sea_orm(string_value = "basic")]
    Basic,
    #[sea_orm(string_value = "advanced")]
    Advanced,
    #[sea_orm(string_value = "expert")]
    Expert,
    #[sea_orm(string_value = "master")]
    Master,
}
