[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
getset.workspace = true
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true
mockall.workspace = true
