[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
chrono.workspace = true
getset.workspace = true
mockall.workspace = true
thiserror.workspace = true
