name: Database Migration

on:
  push:
    branches:
      - main
    paths:
      - renovate.json
      - auth0/**
      - Cargo.lock
      - Cargo.toml
      - crates/**
      - rust-toolchain.toml
      - .github/workflows/migration.yml
      - .github/workflows/**
      - Dockerfile.prod
      - compose.yml
      - compose.prod.yml
  pull_request:
    paths:
      - renovate.json
      - auth0/**
      - Cargo.lock
      - Cargo.toml
      - crates/**
      - rust-toolchain.toml
      - .github/workflows/migration.yml
      - .github/workflows/**
      - Dockerfile.prod
      - compose.yml
      - compose.prod.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  migration:
    name: database migration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
        env:
          POSTGRES_DB: xlair
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d xlair"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: Cache cargo directories
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-migration-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-migration-

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run migrations
        run: cargo run -p migration --locked -- up
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/xlair
