name: Database Migration

on:
  push:
    branches:
      - main
    paths:
      - Cargo.lock
      - Cargo.toml
      - crates/migration/**
      - rust-toolchain.toml
      - .github/workflows/migration.yml
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
      - crates/migration/**
      - rust-toolchain.toml
      - .github/workflows/migration.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  migration:
    name: database migration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16@sha256:f1c3376c26f2609ab9f29f71f824103fe2fcd8ee0346485cb6122a4f93df6f94
        env:
          POSTGRES_DB: xlair
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d xlair"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: Cache cargo directories
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-migration-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-migration-

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run migrations
        run: cargo run -p migration --locked -- up
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/xlair
